export default Object.freeze({
  CREATE_NEW_FEED_START: 'CREATE_NEW_FEED_START',
  CREATE_NEW_FEED_SUCCESS: 'CREATE_NEW_FEED_SUCCESS',
  CREATE_NEW_FEED_FAILED: 'CREATE_NEW_FEED_FAILED',

  GET_FEEDS_START: 'GET_FEEDS_START',
  GET_FEEDS_SUCCESS: 'GET_FEEDS_SUCCESS',
  GET_FEEDS_FAILED: 'GET_FEEDS_FAILED'
});
